version: "3.9"
   
services:

  db:
    image: postgres    
    env_file:
      - .docker.env
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: app-database
        target: /var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
  
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - .docker.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A myproject worker -l info
    user: nobody
    volumes:
      - .:/usr/src/app
    env_file:
      - .docker.env
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1

  

#####################################################################################
# NON ESSENTIALS
#####################################################################################
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   restart: always
  #   env_file:
  #     - .docker.env
  #   ports:
  #   - "8081:8081"
  #   depends_on:
  #     - redis

  celery-beat:
    build: .
    command: celery -A myproject beat -l info
    volumes:
      - .:/usr/src/app
    env_file:
      - .docker.env
    depends_on:
      - db
      - redis

volumes:
  app-database:
    name: app-database